### ISSUE TITLE
Add center button

### ISSUE THREAD

**Issue by willismonroe** [willismonroe/anax#5]
Sometimes you get kind of lost, a button to center back on the selected markers would be handy.

**Comment by pulkitxm** [comment]
Can I get assigned? let me know how to start

**Comment by vishalpawarR** [comment]
@willismonroe Please give the steps to reproducing the issues or some screenshot explaining the issues!

**Comment by willismonroe** [comment]
Partially solved by https://github.com/willismonroe/anax/pull/6

**Comment by janup2442** [comment]
i would like to contribute in it. Please guide me for the same.
where and which button  , I have to center???


i am currently looking in Index.html file but there is nothing. do let me know , where ??  do i have to create a button first and make it center.

**Comment by willismonroe** [comment]
@janup2442 The project is a VueJS project there is no code in the index.html file, you should look at App.vue and its dependencies.

**Comment by vrishtrix** [comment]
> Partially solved by #6

@willismonroe It seems that this issue has been solved already. Can you please elaborate on what needs to be added on top of #6 since you mentioned it was "partially" solved.
